web/router.ex
defmodule Hospital.Router do
  use Hospital.Web, :router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  scope "/", Hospital do
    pipe_through [:browser, :browser_session] # Use the default browser stack

    # Account endpoints
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :delete, as: :logout
    get "/account", UserController, :show, as: :account
    post "/signup", UserController, :create, as: :signup

    # Frontend API endpoints
    resources "/health_checks", HealthCheckController
    get "/reports", ReportSummaryController, :index

    # Catch-all defers to Redux router
    get "/:none", PageController, :index
    get "/", PageController, :index, as: :index
  end

  scope "/api", Hospital do
    pipe_through :api

    post "/reports", Api.ReportController, :create, as: :report_api
    get "/health_checks", Api.HealthCheckController, :index, as: :health_check_api
  end
end

web/controllers/session_controller.ex
defmodule Hospital.SessionController do
  use Hospital.Web, :controller

  alias Hospital.User

  plug :scrub_params, "user" when action in [:create]

  def create(conn, params = %{}) do
    user = User.from_email(params["user"]["email"] || "")
    if user do
      changeset = User.login_changeset(user, params["user"])
      if changeset.valid? do
        conn = Guardian.Plug.sign_in(conn, user, :token, perms: %{ default: Guardian.Permissions.max })
        token = Guardian.Plug.current_token(conn)

        conn
        |> render(Hospital.UserView, "show.json", user: Map.put(user, :token, token))
      else
        conn
        |> put_status(401)
        |> render(Hospital.UserView, "error.json", error: "Bad login.")
      end
    else
      conn
      |> put_status(401)
      |> render(Hospital.UserView, "error.json", error: "Login not found.")
    end
  end

  def delete(conn, _params) do
    Guardian.Plug.sign_out(conn)
    |> put_flash(:info, "Logged out successfully.")
    |> redirect(to: login_path(conn, :new))
  end

  def unauthenticated_api(conn, _params \\ :empty) do
    the_conn = put_status(conn, 401)
    case Guardian.Plug.claims(conn) do
      { :error, :no_session } -> json(the_conn, %{ error: "Login required" })
      { :error, reason } -> json(the_conn, %{ error: reason })
      _ -> json(the_conn, %{ error: "Login required" })
    end
  end

  def forbidden_api(conn, _ \\ :empty) do
    conn
    |> put_status(403)
    |> json(%{ error: :forbidden })
    |> halt
  end

  def forbidden(conn, _) do
    conn
    |> put_status(403)
    |> put_flash(:error, "Forbidden")
    #|> redirect(to: page_path(conn, :index))
  end
end

web/views/session_view.ex
defmodule Hospital.SessionView do
  use Hospital.Web, :view
end

web/templates/session/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-offset-4 col-md-4 form-signin">
      <form class="form-signin">
        <h2 class="form-signin-heading">Account Login</h2>
        <%= email_input f, :email, class: "form-control", placeholder: "email" %>
        <%= password_input f, :password, class: "form-control", placeholder: "password" %>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <%= submit "Login", class: "btn btn-lg btn-primary btn-block" %>
        Need an account? <a href="<%= signup_path(@conn, :new) %>">Register here</a>
      </form>
    </div>
  </div>
<% end %>

web/templates/session/new.html.eex
<%= render "form.html", changeset: @changeset,
                        conn: @conn,
                        action: login_path(@conn, :create) %>